### ISSUE TITLE
Incorporate the Events stats API endpoint

### ISSUE THREAD

**Issue by tclavelle** [GlobalFishingWatch/gfwr#105]
The Events API now has an [events statistics endpoint](https://globalfishingwatch.org/our-apis/documentation#statistics-on-events-post) to get statistics on different event types worldwide or in a specific region. Need to add a `gfwr` function to call this endpoint.

**Comment by tclavelle** [comment]
Note: incorporate into `dev` using v3 of APIs, not v2

**Comment by AndreaSanchezTapia** [comment]
closing as completed
