### ISSUE TITLE
get_raster() does not work when group_by = "mmsi" or  "vessel_id"

### ISSUE THREAD

**Issue by Avocetta** [GlobalFishingWatch/gfwr#113]
Hi GFW,

When I use get_raster() it returns this error when group_by is "mmsi" or "vessel_id":
Error in `httr2::req_perform()`:
! HTTP 422 Unprocessable Entity.
• Not found vessel datasets associated

The function still works when group_by = "flag", "gearType", or "flagAndGearType".

e.g.
get_raster(spatial_resolution = 'low',
           temporal_resolution = 'yearly',
           group_by = 'vessel_id',
           date_range = '2021-01-01,2021-10-01',
           region = 5677,
           region_source = 'eez',
           key = key)

Thanks for all your hard work

**Comment by AndreaSanchezTapia** [comment]
Thanks for flagging this issue, @Avocetta. The current release of **gfwr** is running on version 2 of our APIs, which will be no longer maintained by our API team, but I have let them know of this issue.
We are working towards updating gfwr to version 3, where this functionality is still working. We will let you know when we complete this update. Thanks for your patience!

**Comment by AndreaSanchezTapia** [comment]
Fixed now from production. Closing this issue. @Avocetta please let us know if you have any other problem, thank you.
