### ISSUE TITLE
Forbidden for all datasets except public-global-fishing-events:latest

### ISSUE THREAD

**Issue by davidshumway** [GlobalFishingWatch/gfwr#124]
Whenever I access `4wings` with anything but the `public-global-fishing-events:latest` dataset, I'm receiving this error:

```bash
{"statusCode":403,"error":"Forbidden","messages":[{"title":"Forbidden","detail":"Insufficient permissions for <DATASET> datasets"}]}
```

Example query:
```bash
curl --location -g --request POST 'https://gateway.api.globalfishingwatch.org/v3/4wings/report?spatial-resolution=HIGH&temporal-resolution=HOURLY&group-by=FLAG&datasets[0]=public-global-port-visits-c2-events:latest&&date-range=2017-01-01T00:00:00.000Z,2018-01-01T00:00:00.000Z&format=JSON'\
  -H "Authorization: Bearer [token]"\
  --data-raw '{"geojson":{"type":"Polygon","coordinates":[[[...,...], [...,...], [...,...], [...,...], [...,...]]]}}'\
  --output 'test.json'
```

Output:
```bash
{"statusCode":403,"error":"Forbidden","messages":[{"title":"Forbidden","detail":"Insufficient permissions for public-global-port-visits-c2-events:latest datasets"}]}
```
Is this because I just opened my account? Or are certain datasets off-limits?

**Comment by AndreaSanchezTapia** [comment]
Hello @davidshumway as you can see in [this](https://globalfishingwatch.org/our-apis/documentation#api-dataset) API documentation page, the only dataset for the 4wings endpoint is `public-global-fishing-effort:latest`. The other datasets can be accessed via the Events and Vessels endpoints.

**Comment by AndreaSanchezTapia** [comment]
I'm closing this but let us know if you have an other questions.
