### ISSUE TITLE
The output problem of function get_vessel_info

### ISSUE THREAD

**Issue by Wangdonley** [GlobalFishingWatch/gfwr#125]
get_vessel_info can only obtain up to 10000 pieces of data. What should be done when the data volume exceeds 10000.

**Comment by AndreaSanchezTapia** [comment]
Hi, this is a limitation of the API, you cannot send a string that is too long. If you need to do a larger query, loop over your vessel identifiers vector and do several calls instead of doing a single long query.

**Comment by AndreaSanchezTapia** [comment]
I will close this issue but feel free to reopen if you have any further questions.
