### ISSUE TITLE
Unexpected content type

### ISSUE THREAD

**Issue by orowley** [GlobalFishingWatch/gfwr#128]
Kia Ora,

Wanting some assistance with the below error code when pulling data for a user defined json using the get_raster() function

Error in `httr2::req_perform()`:
! Failed to parse error body with method defined in `req_error()`.
Caused by error in `httr2::resp_body_json()`:
! Unexpected content type "text/html".
• Expecting type "application/json" or suffix "json".

**Comment by giselamo** [comment]
Hi @orowley Thank you for bringing this bug to our attention. Typically, this occurs when the request involves a large or intricate polygon, or encompasses multiple years or datasets (as illustrated in the example provided in the [API errors section](https://globalfishingwatch.org/our-apis/documentation#errors-codes), see image attached. 
![Screenshot from 2024-04-16 11-21-47](https://github.com/GlobalFishingWatch/gfwr/assets/1828158/4ab7ee2e-b79d-4633-bbab-495ee81ebcf5)
). To help us investigate further, could you kindly provide the polygon and the specific request parameters you were using? Thanks!

**Comment by AndreaSanchezTapia** [comment]
Thanks for flagging this. I just encountered the same error with

get_event(event_type = "PORT_VISIT",
            vessels = c("e0c9823749264a129d6b47a7aabce377",
             "8c7304226-6c71-edbe-0b63-c246734b3c01"),
             start_date = "2017-01-26",
             end_date = "2017-12-31",
             confidence = c(3, 4), # only for port visits
             key = gfw_auth())

**Comment by AndreaSanchezTapia** [comment]
Hi @orowley thanks for flagging this issue. The most recent version of the package will be released on June 30th and this should not happen again, so I'm closing this issue. Please feel free to reopen if you encounter it again after installing the next version.

**Comment by orowley** [comment]
Awesome this is fantastic news and will make using the API through R so much easier for my team with our far reaching birds and large datasets!

Keep up the awesome work.
