### ISSUE TITLE
Add support for other region types to get_raster

### ISSUE THREAD

**Issue by gmcdonald-sfg** [GlobalFishingWatch/gfwr#37]
I don't know if it would be possible with the current API infrastructure, but it would be great to have built-in support for other region types in `get_raster`. Currently, you can use your own json or an EEZ id in the `shape_json` argument. But could we also specify something like `mregion`, `mpant`, `rfmo`, `fao`, `fao_major`, or `ocean`?

I know Tyler said in his email:

```
At this stage, we are not able to add new data fields returned by the API, so please focus feedback on the current data/format returned by the various functions. 
```

This is a bit different though. I think the data fields output of `get_raster_ sound fine, but it would be great to specify different spatial areas in the input. Just not sure if this is possible with the current API infrastructure.

**Comment by tclavelle** [comment]
Closing as we've addressed several region types. Can open more specific region issues in the future.
