### ISSUE TITLE
Custom region sources for `get_raster`

### ISSUE THREAD

**Issue by sirsimmon** [GlobalFishingWatch/gfwr#68]
When using `get_raster` with a custom json, I'm running into the following message:

      <error/rlang_error>
      Error in `abort()`:
      ! `message` must be a character vector, not a list.
      ---
      Backtrace:
           ▆
        1. ├─gfwr::get_raster(...)
        2. │ └─... %>% httr2::resp_body_raw(.)
        3. ├─httr2::resp_body_raw(.)
        4. │ └─httr2:::check_response(resp)
        5. │   └─httr2:::is_response(req)
        6. └─httr2::req_perform(.)
        7.   └─httr2:::resp_abort(resp, error_body(req, resp))
        8.     └─rlang::abort(message = c(message, resp_auth_message(resp), info))
        9.       └─rlang:::validate_signal_args(...)
       10.         └─rlang:::check_character(message, call = env)
       11.           └─rlang:::stop_input_type(x, what, ..., arg = arg, call = call)
       12.             └─rlang::abort(message, ..., call = call, arg = arg)

This seems to be due to my json being a Multipolygon type rather than Polygon as used in the example in the readme. 
i.e.: 
`my_json <- '{"geometry":{"type":"MultiPolygon","coordinates": [ etc`
vs 
`'{"geojson":{"type":"Polygon","coordinates": [ etc`

I'm trying to pull data based on FAO Major Fishing Areas (and Subareas), mainly parts of the Mediterranean, so I've tried using the json and shapefiles from the FAO, and my own json created in GIS. All methods eventually result in the same error shown above.

Using a simple polygon like `'{"geojson":{"type":"Polygon","coordinates": [[[-7,29], [-7,45], [36,45], [36,29], [-7,29]]]}}'` presents no problem, and extracting a single small polygon from the FAO multipolygon json also runs without error. This lead me to believe the issue is with the multipolygon aspect, or perhaps the complexity of the shapes involved. 

Should these types of shapes work with `get_raster` and I'm doing something wrong? 
Is there a different way to pull data for a large complex region that isn't a specific argument like `eez` or `mpa`?

[Here](https://github.com/GlobalFishingWatch/gfwr/files/9293238/FSA_37.zip) are a json and shapefile that I've had trouble with.

**Comment by natemiller** [comment]
@sirsimmon Sorry for the delay in getting back to you on this. You are correct that the issue appears to be in the format of the geojson file. Our API does work with Multipolygon files, but they have to be in the format shown here 
```
multipolygon_shape = '{
    "geojson": { 
  "type": "MultiPolygon",
  "coordinates": [
    [[[102.0, 2.0], [103.0, 2.0], [103.0, 3.0], [102.0, 3.0], [102.0, 2.0]]],
    [[[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]],
     [[100.2, 0.2], [100.8, 0.2], [100.8, 0.8], [100.2, 0.8], [100.2, 0.2]]]
  ]
}
}'
```
This is not made clear in the `gfwr` documentation and is something we will seek to address. I have had an attempt at reformatting the json you provided so that it will work with the API. 
```
readr::read_file('FSA_37/FSA_37.json') %>%
  as.character(.) %>%
  paste0('{"geojson":', . , '}') %>%
  get_raster(spatial_resolution = 'low',
           temporal_resolution = 'daily',
           group_by = 'flag',
           date_range = '2022-01-01,2022-02-01',
           region = .,
           region_source = 'user_json',
           key = gfw_auth())
```
