### ISSUE TITLE
group_by in get_raster()

### ISSUE THREAD

**Issue by shinnakayama** [GlobalFishingWatch/gfwr#78]
Hello GFW,

In the example,
```
# use EEZ function to get EEZ code of Cote d'Ivoire
code_eez <- get_region_id(region_name = 'CIV', region_source = 'eez', key = key)

get_raster(spatial_resolution = 'low',
           temporal_resolution = 'yearly',
           group_by = 'flag',
           date_range = '2021-01-01,2021-10-01',
           region = code_eez$id,
           region_source = 'eez',
           key = key)
```
Removing `group_by` gives an error (I want all fishing hours). Also, `group_by = 'geartype'` gives an error.

**Comment by natemiller** [comment]
@shinnakayama 
Unfortunately as described in the [API documentation](https://globalfishingwatch.org/our-apis/documentation#create-a-report-of-a-specified-region) the `group_by` field is currently required.   
  
There is a typo in the `gfwr` documentation which we will fix. To group by geartype you must use the parameter `gearType` (note the camelcase).

**Comment by natemiller** [comment]
I have changed the documentation for get_raster to make it clear that gear type grouping must be specified as `gearType`
