### ISSUE TITLE
Convert `paginate()` function to general `gfw_api_request()` function

### ISSUE THREAD

**Issue by tclavelle** [GlobalFishingWatch/gfwr#9]
Currently, we are running an API call first and then passing the response to `paginate()`. Instead, we should have a more general function that 1) makes the initial API call; and 2) paginates additional responses if needed.

**Comment by tclavelle** [comment]
`paginate()` now handles all necessary API requests to retrieve the full result set. Last step is to rename the function along the lines of the issue title.

**Comment by AndreaSanchezTapia** [comment]
This is such a key function that I think it should have its own .R file and not be inside utils.R, in addition to renaming it, @tclavelle 

I'll open another issue to talk about the sequence of merges.
