### ISSUE TITLE
Cause of "Error in abort()" message?

### ISSUE THREAD

**Issue by adeloera** [GlobalFishingWatch/gfwr#91]
Hi! I'm wondering if the cause of the an error message "Error in `abort()`: A message must be a character vector, not a list." is known. I get it occasionally, but also inconsistently, on `get_events()` calls for fishing events. Sometimes I get it when trying to extract events as part of a loop, but the code runs fine outside of a loop. Not really sure what is going on there--curious if anyone knows what I could do! 

![image](https://user-images.githubusercontent.com/32284808/198720924-75115bea-bf26-4e2e-9f5b-5e2379012773.png)

**Comment by adeloera** [comment]
For what it's worth this particular time I got it trying to run `fishing_events <- get_event(event_type = "fishing", start_date = "2016-01-01", end_date = "2016-12-31")` 

But I've gotten it before on much smaller calls when trying to loop through several vessels and extract all their fishing events.

**Comment by eastonwhite** [comment]
The issue appears to still come up when using region_source = 'trfmo' even if using a short time frame. I am guessing this is due to the larger spatial range.

**Comment by tclavelle** [comment]
This was addressed by PR #100. Use `region_source = 'rfmo'` now because there are non-tuna RFMOs that can specified.
