### ISSUE TITLE
Adjust Search Start and End Handling

### ISSUE THREAD

**Issue by adeloera** [GlobalFishingWatch/gfwr#92]
Hi! I am a huge fan of GFWR and have been working with it for the last several months. I have a few suggestions for things that would be helpful additions or modifications, though of course I recognize that these may be too big of asks. Apologies if it is inappropriate, but I think this is in the purview of the contribution guide. 

Currently, I believe the `start_date` and `end_date` given to the `get_events` function are hard bounds: the function will return events which begin after 12:00am on the start date and end before midnight preceding the end date. I think it would be useful to have some way to extract all the events that had some time between the start and end date, regardless of whether the entire event occurred between those bounds. Currently, if I do a `get_events` calls from 2020-01-05 to 2020-01-10 I would not get any events which, say, began on 2020-01-04 but continued into the period or any events which began during the period and ended after. For my purposes this makes it difficult to loop over dates to extract events, since events are lost if they don't fit entire between date ranges. I can also imagine this being problematic for other stakeholders: if I want to see fishing effort on a certain day, it might be uninformative to show only those fishing events that began and ended in that same day. One fix to at least allow for looping over dates would be to return all events which began between the start and end date, though admittedly this would still miss some events that occurred partially during the time period. 

Anyway, just wanted to flag this as a potential improvement to an already really great public good! Thank you!

**Comment by tclavelle** [comment]
@natemiller @rociojoo [Slack thread](https://globalfishingwatch.slack.com/archives/C01D4A1AZ5Z/p1667995441651519) describing the change in the APIs.

**Comment by adeloera** [comment]
Has the handling of the `get_events` function changed?

**Comment by adeloera** [comment]
@giselamo I get the same result, thanks! If easy to implement it would be useful to be able to specify whether the function uses hard bounds or not. For example I am looping over several months trying to extract the fishing events. To make sure I get them all it would be great is the function returned every event that began in each month, even if it didn't end in it, but I also don't want to double count events that began in January and ended in February. So at least for that purpose it would be useful to specify a "hard" start bound and a "soft" end bound.

**Comment by tclavelle** [comment]
Closing for now, @giselamo as this is more of an API feature request rather than a specific `gfwr` issue.
