### ISSUE TITLE
Specify Vessel Type in get_events Call

### ISSUE THREAD

**Issue by adeloera** [GlobalFishingWatch/gfwr#93]
Another functionality which I think would be really helpful to have in the `get_events` function is the ability to specify the vessel type. Currently I am trying to get port events for fishing vessels within a certain date range, and it would be nice to be able to just specify that I only want fishing vessels ex ante, rather than loading them all in and then filtering some events out by the `vessel_type` found under the `vessel` variable.

**Comment by tclavelle** [comment]
Another API feature consideration, @giselamo

**Comment by giselamo** [comment]
Added in our API and Data feedback board for planning https://feedback.globalfishingwatch.org/data-requests/p/filtering-event-dates

**Comment by AndreaSanchezTapia** [comment]
I am closing this issue since the migration to v3 and this feature will be available. Please feel free to reopen if anything fails or you have a question.
