### ISSUE TITLE
Can we add filter to get_raster?

### ISSUE THREAD

**Issue by rollan13** [GlobalFishingWatch/gfwr#97]
It would be great if we can filter `get_raster` by flag and geartype, similar to `get_vessel_info`. 
The GFW API includes a similar filter: https://globalfishingwatch.org/our-apis/documentation#create-a-report-of-a-specified-region

**Comment by natemiller** [comment]
Seems like we should be able simply add a filter parameter which specifies a value for `filters[0]` in the endpoint

**Comment by natemiller** [comment]
This issue has been addressed by #98
